### ISSUE TITLE
Using Oscar+ original repo models produces bad captions

### ISSUE THREAD

**Issue by l3bjorge** [Alcoholrithm/Oscar_Scripts#3]
Hi again!

I have been using your code and models with vinvl detections and getting good results so far but when I try to use a checkpoint from the original Oscar repository I get terrible captions.

I'm trying the model trained on COCO for image captioning finetuned with cross entropy that they have available on their VinVLModelZoo.md

https://biglmdiag.blob.core.windows.net/vinvl/model_ckpts/image_captioning/coco_captioning_large_xe.zip

I used this image again:
![perro_frisbee](https://user-images.githubusercontent.com/25321261/147083886-39bbec70-a946-499b-ab1e-384cff80ac68.jpg)

This is the caption I got from your model finetuned with CIDER optimization:
['a small brown bear standing on top of a sandy beach.']

This is the caption I get with the model from Oscar's repo:
['a large number of lights that are on a building.']

I also manually checked what detections was vinvl finding from their original repository on this same image and got really good results:
![perrofrisbee_x152c4 attr](https://user-images.githubusercontent.com/25321261/147084446-08444cbf-0145-4913-b57b-2a1857620ee6.jpg)

[perrofrisbee_x152c4.attr.txt](https://github.com/Alcoholrithm/Oscar_Scripts/files/7762252/perrofrisbee_x152c4.attr.txt)

I should also mention I made a few changes in the code to run it in cpu instead of cuda since the model can't fit in the gpu I have available.

I want to check what results I can get with the best performing model from their repository (41.0 BLEU4 score) but I think I'm missing something.

Do you think you can help me with this?

Thanks for the help once again.

**Comment by Alcoholrithm** [comment]
Hi
Sorry for answering late.
The encoder must be same one which was used for training decoder model.
However, the scene graph repo's vinvl model is thought to be different from the model used by the author of the Oscar+ paper.
So you got wrong feature vectors which made wrong captions.
Since they do not provide their encoder model there is no other way but to modify the training script and train again to get better performance.
Happy new year
